spring.application.name=ttc-manager

# ========================
# Datenbank-Konfiguration
# ========================

spring.datasource.url=jdbc:postgresql://localhost:5432/ttc_manager
spring.datasource.username=${DB_USERNAME:ttc_user}
spring.datasource.password=${DB_PASSWORD:2511}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================
# Server
# ========================

server.port=8081

# ========================
# Frontend / CORS
# ========================

app.frontend.base-url=${FRONTEND_BASE_URL:http://localhost:5173}